### ISSUE TITLE
Hitsound Copier usage question

### ISSUE THREAD

**Issue by ns920** [mappingtools/mappingtools.github.io#4]
It seems like mute sliderends doesn't effective when copy hitsounds is true. I had checked if copy hitsounds is true then all hitobjects' CanCopy will be false. Is it a bug or just a feature?

**Comment by OliBomby** [comment]
It's a feature. The mute sliderends feature is supposed to not mute sliderends which have received hitsounds from the beatmap you copied hitsound from.
